# Kickoff default config

# Characters shown in front of the query.
prompt = 'Enter password: '

# space between window border and the content in pixel
padding = 100

# font = ''        # has been deprecated in favour of fonts list
fonts = ['RobotoMono Nerd Font', 'Noto Sans Mono']     # list of otf or ttf fonts. later elements work as fallback
font_size = 32.0

[history]
decrease_interval = 48 # interval to decrease the number of launches

[colors]
# color format: rgb or rgba, if transparency is desired
background = '#282c34FF'
prompt = '#abb2bfff'
text = '#ffffff00'          # for search results
text_query = '#55555500'    # for the search query
text_selected = '#282c34FF' # for the currently selected result

[keybindings]
# keybindings syntax: ctrl/shift/alt/logo as modifiers and a key joined by '+' signs
# A list of available keys can be found here: https://docs.rs/crate/x11-keysymdef/0.2.0/source/src/keysym.json
paste = ["ctrl+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace", "ctrl+w", "ctrl+u"]
complete = []
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
