#!/usr/bin/env bash

sudo nixos-rebuild switch --flake ~/.dotfiles/ || exit 1
previous_config=$(ls -1 --sort=time /nix/var/nix/profiles/ | head -n 3 | tail -n 1)
nvd diff "/nix/var/nix/profiles/$previous_config" /nix/var/nix/profiles/system
